version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: envio_production
      POSTGRES_USER: envio
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U envio -d envio_production"]
      interval: 10s
      timeout: 5s
      retries: 5

  envio:
    build:
      context: .
      dockerfile: Dockerfile.envio
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: envio_production
      POSTGRES_USER: envio
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_change_me}
      NODE_ENV: production
      ENVIO_RPC_URL: https://testnet-rpc.monad.xyz
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local